version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: petfinder-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongo:27017/petfinder
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./backend-logs:/var/log/petfinder  # ✅ log folder mounted to host

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: petfinder-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    environment:
      - NODE_ENV=production

volumes:
  mongo-data:
