version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: petfinder-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: petfinder-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
