version: "3.8"
services:
  backend:
    build: ./backend
    image: yourdockerhubusername/pet-backend:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    image: yourdockerhubusername/pet-frontend:latest
    restart: always
    ports:
      - "80:80"
